disabled_rules: # rule identifiers to exclude from running
  - colon
  - comma
  - control_statement
  - closure_parameter_position
  - trailing_whitespace
  - force_cast
  - force_try
#  - force_unwrapping
  - type_body_length
  - opening_brace
  - identifier_name
  - statement_position
  - trailing_semicolon
  - shorthand_operator
  - line_length
  - file_length
  - function_parameter_count
  - orphaned_doc_comment
  - trailing_newline
  - void_return
  - vertical_whitespace
  - function_body_length
  - return_arrow_whitespace
  - unused_closure_parameter
  - large_tuple
  - weak_delegate
  - unused_setter_value
  - unneeded_break_in_switch
  - type_name
  - class_delegate_protocol
  - leading_whitespace
  - operator_whitespace
  - redundant_void_return
  - empty_collection_literal
  - closing_brace
  - no_space_in_method_call
  - trailing_comma
  - unused_optional_binding
  - trailing_closure
  - redundant_discardable_let
  - legacy_constructor
  - mark
  - implicit_getter
  - multiple_closures_with_trailing_closure
  - empty_parentheses_with_trailing_closure
  - vertical_parameter_alignment
  - private_over_fileprivate


opt_in_rules: # some rules are only opt-in
  - unavailable_function
# Find all the available rules by running:
# swiftlint rule

